# Jekyll 설정 파일
title: n8n 뉴스레터 자동화 가이드
description: n8n 워크플로우를 활용한 뉴스레터 자동화 시스템 구축 가이드
author: GPTers

# 테마 설정
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light

# 언어 설정
lang: ko-KR

# URL 설정 (GitHub Pages 사용 시)
baseurl: "/n8n-newsletter" # 저장소 이름
url: "" # GitHub Pages URL이 자동으로 설정됨

# 플러그인
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# 검색 설정
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# 헤더 링크
aux_links:
  "GitHub":
    - "//github.com/AI-GameDev/n8n-newsletter"

# 푸터
footer_content: "Copyright &copy; 2025 n8n 뉴스레터 자동화 가이드"

# 네비게이션 설정
nav_enabled: true
nav_sort: case_sensitive

# 마크다운 설정
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# 파일 제외
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Collections 설정 (선택사항)
collections:
  docs:
    permalink: "/:path/"
    output: true

# 기본값 설정
defaults:
  - scope:
      path: ""
    values:
      layout: default
      nav_order: 1